### ISSUE TITLE
Multi AFK Question

### ISSUE THREAD

**Issue by LuisBlock69** [Sleepydragn1/twitchAFK#11]
**Is it possible to run more than one instance on different channels? If so, how to do it? Otherwise, I leave it as a suggestion. I appreciate the attention.**

**Comment by Sleepydragn1** [comment]
Channels can be specified via the last argument in the command, so you just need to run two different instances with slightly different commands.

For example, this would start one instance that AFKs https://www.twitch.tv/sleepydragn1:

`` slimerjs --headless -P [SlimerJS profile name here] twitchAFK.js sleepydragn1 ``

Then, running this command separately would start another instance that AFKs https://www.twitch.tv/vinesauce:

`` slimerjs --headless -P [SlimerJS profile name here] twitchAFK.js vinesauce ``

Do note that if your intent is to get drops using this script, you can only qualify for drops on one channel at a time. You could set up two Twitch accounts, but obviously you can't link the same game account to both of them. Thus, you'd also need a second account for that game, which may not be favorable depending on your intent.

**Comment by LuisBlock69** [comment]
I tried to do this, but it always happens: XULRunner. SlimerJS is already running, but is not responding. The old SlimerJS process must be finalized to open a new window. What to do?

**Comment by Sleepydragn1** [comment]
Well, this is what happens when I don't try out the advice I'm giving out before I actually write it up. I remembered previously running multiple instances in tandem and simply assumed that it would work under all circumstances. 

What I didn't know up until now is that each profile can only be mapped to a single instance. [Apparently, when you're not using a profile, SlimerJS just creates a new, temporary profile to avoid this problem.](https://docs.slimerjs.org/current/configuration.html#profiles) As such, each simultaneous instance that you run will need its own profile. So you'll probably want to use ```slimerjs --CreateProfile [new profile name]``` to create *another* profile, and use that for the second instance.

Next time I update the README I'll include a footnote reflecting this to avoid further confusion.

**Comment by LuisBlock69** [comment]
**Hell yeah! Now its working like a charm. Thank you to help me with this <3. Congratulations for create this wonderful project, i really appreciated.**
