### ISSUE TITLE
Where are my profiles located at?

### ISSUE THREAD

**Issue by deffizin** [Sleepydragn1/twitchAFK#12]
Does it have a file or something?

**Comment by Sleepydragn1** [comment]
Each profile has its own folder, but that folder's location depends on your OS.

[According to SlimerJS' documentation on profiles,](https://docs.slimerjs.org/current/configuration.html#profiles) they should be located in ```$HOME/.innophi/slimerjs/```, but I found that mine were located in ```C:\Users\[username]\AppData\Roaming\Innophi\SlimerJS\Profiles```. This is probably a Linux vs. Windows issue, I imagine.

Otherwise, it should be easy to find where they're located if you run ```slimerjs -P``` with no additional arguments, as it'll pop up a window that allows you to select or manage your profiles. Hovering over an existing profile will give you the file path of that profile.

**Comment by deffizin** [comment]
Thanks!
