### ISSUE TITLE
Surprisingly high ram and cpu use?

### ISSUE THREAD

**Issue by freshfriedfish** [Sleepydragn1/twitchAFK#17]
![image](https://user-images.githubusercontent.com/33766008/97783880-fa9fdd00-1b70-11eb-8d0d-43065ce4a263.png)

Is this normal? Didn't expect it to use up so much ram, the script works perfectly though :) . P.S they are all spamming typeerror

**Comment by Sleepydragn1** [comment]
The TypeError issue is related to #16, and should be fixed in the next push.

I'm going to assume that you're running multiple instances here, since that's what the Task Manager layout looks like to me.

The memory use is about right for my machine, and both the latest Firefox and Firefox 59.0.3 (which SlimerJS uses) utilize about that much RAM when opening Twitch on their own.

Your CPU usage appears to be a little high, but it could be due to a difference in your processor versus mine. I'm running a Ryzen 7 3700X, to give some context. On my machine, it uses up 5% on average for one instance, with occasional dips to 4% and occasional spikes up to 10%. This matches (and actually undercuts) Twitch's performance on Firefox 59.0.3, although it seems that the latest version of Firefox uses far less CPU power.

This seems fairly reasonable to me, since each instance of twitchAFK is streaming a video/audio stream and rendering it, which is a somewhat intensive process.

**Comment by freshfriedfish** [comment]
Any way to decrease resources use? Because i can run far more accounts on chrome than the script. prefer to keep usign the script  tho

**Comment by Sleepydragn1** [comment]
As I've shown through my own testing, the script adds minimal overhead to Twitch's page rendering. If you think this is incorrect, feel free to do some independent testing — I'm always happy to be proven wrong. This means that any kind of optimization would have to be on the SlimerJS side of things. 

Unfortunately, the performance of SlimerJS is intrinsically tied to its rendering engine, which makes any kind of optimization difficult. The way I see it, there's only a few possibilities here:

**A setting is found within Firefox that magically decreases resource use.**

I don't know of any such setting, but maybe it exists?

**SlimerJS updates to support the latest (and therefore, more optimized) version of Firefox.**

Considering that the SlimerJS repo hasn't been touched in a while, I think this is pretty unlikely. You can actually override SlimerJS to force it to use the latest version of Firefox, but having tested it, I can tell you that it crashes and burns almost immediately.

**It's proven that actually playing/rendering the Twitch stream isn't required to get Twitch drops.**

Not only is this difficult to prove, but I think it's fairly unlikely as well. If it were proven, I'd be willing to *try* adding an option to disable the rendering of the stream, which would likely decrease CPU usage.

Also, while the maxQuality setting _probably_ has an impact on CPU use, it's already set to the minimum by default. If you happened to change it for some reason, setting it back to "MIN" might help a bit.

**Comment by Sleepydragn1** [comment]
Without any other further questions or information, I'm going to close this issue.
