### ISSUE TITLE
The syntax of the command is incorrect.

### ISSUE THREAD

**Issue by imaxisXD** [Sleepydragn1/twitchAFK#8]
getting this error after installing
![Screenshot_1](https://user-images.githubusercontent.com/56172425/79901249-2f4a1380-842d-11ea-9a3f-e4075c176b91.png)
 the latest updated version of the script

**Comment by Sleepydragn1** [comment]
Just to be sure, you added SlimerJS to your PATH variable, right? That'd be my first guess as to what's going wrong, since using the "slimerjs" command without specifying its location requires that SlimerJS' install folder is added to your PATH variable.

If you haven't, [this is a good tutorial explaining how to do it.](https://www.howtogeek.com/118594/how-to-edit-your-system-path-for-easy-command-line-access/)

**Comment by imaxisXD** [comment]
well it was working fine earlier but now after updating its not plus my script and slimerjs are extracted in the same folder 

a request can u make whole installation process youtube video cuz it will help so many people 
thx

**Comment by imaxisXD** [comment]
add this feature please "'I'll add in an option to enable/disable stream volume"

**Comment by imaxisXD** [comment]
I added to environment variable still same error

**Comment by Sleepydragn1** [comment]
Based on another issue you've created where you're having problems within the script, I'm going to assume you got it working and this is now a non-issue. If this is *not* the case, and you're still having trouble, feel free to comment back and I'll re-open it.
